### ISSUE TITLE
"Error writing data to the connection. Error reading data from the connection." exception after deleting the connection

### ISSUE THREAD

**Issue by luronumen** [FirebirdSQL/NETProvider#1095] opened 2023-02-24 11:34 UTC
**Actual Result**
- "_Error writing data to the connection. Error reading data from the connection._" exception after deleting the connection

**Expected Result**
- The connection pool should be re-established in the second attempt without any exceptions

**Steps to Reproduce the Issue**
1. Create the following _ConnectionString_:
> private static string ConnectionString() => new FbConnectionStringBuilder { Pooling = true, ServerType = FbServerType.Default, DataSource = "LOCALHOST", Database = "BOTSERVICE_CIN", Charset = "UTF8", Role = "RDB$ADMIN" }.ConnectionString;
2. Create the following _SelectProcedure_ method:
> private static bool SelectProcedure(string procedureName, string[] inputParameters, out DataTable dataTable, bool poolingStatus = true)
    {
        dataTable = new DataTable();
        try
        {
            using var fbConnection = new FbConnection(ConnectionString());
            using var fbCommand = new FbCommand(procedureName, fbConnection);
            fbCommand.CommandType = CommandType.StoredProcedure;
            //INPUT PARAMETERS
            for (var i = 0; i < inputParameters.Length; i++)
                fbCommand.Parameters.Add("@" + i, inputParameters[i]?.Normalize()).Direction = ParameterDirection.Input;
            //OPEN CONNECTION
            fbConnection.Open();
            //SELECT PROCEDURE
            using (var fbDataReader = fbCommand.ExecuteReader())
                dataTable.Load(fbDataReader);
            return true;
        }
        catch (FbException fbException)
        {
            if (poolingStatus)
                return SelectProcedure(procedureName, inputParameters, out dataTable, false);
            Console.WriteLine($"\"Database - Select Procedure\" exception: {fbException.Message}");
            return false;
        }
    }
3. Run the _SelectProcedure_ method: Verify that no issue happen
> SelectProcedure("B_CURRENCYEXCHANGES_API", Array.Empty<string>(), out dataTable)
4. While the application is running open BOTSERVICE_CIN database using the FlameRobin and run the following query:
> DELETE FROM MON$ATTACHMENTS WHERE MON$ATTACHMENTS.MON$SYSTEM_FLAG=0 AND MON$ATTACHMENT_ID<>CURRENT_CONNECTION;
5. Run the _SelectProcedure_ method again: Verify that the issue happen
> SelectProcedure("B_CURRENCYEXCHANGES_API", Array.Empty<string>(), out dataTable)

**Important Notes**
- This issue does not happen if Stop/Start FirebirdSQL service;
- This issue does not happen if the FirebirdSQL service is in other PC and the client PC lost the database connection;

**Environment Setup** 
- .NET 7.0
- Firebird SQL 3.0.10
- FirebirdSql.Data.FirebirdClient 9.1.1

**Comment by cincuranet** [comment] 2023-02-24 13:13
> The connection pool should be re-established in the second attempt without any exceptions

That's exactly what's not 100% reliably possible. Even if I check that the connection is OK, the second I give it to you, the connection might become broken. Hence you'd still need to have some recovery logic in place (in fact this was even described in ADO.NET/SqlClient documentation).

**Comment by luronumen** [comment] 2023-02-24 20:40
Hi @cincuranet 

Many thanks for your quick response!

It wasn't clear to me from reading your comment whether you considered this to be a valid issue.

Note that when calling the _SelectProcedure_ method after deleting the connection pool on the server side, an _FbException_ is expected to occur in the _try block_ of the method that is handled in the _catch block_. Note that in the _catch block_ the method is called again, for the second time, and it is precisely here in this second call where a new connection pool should be opened and no more exceptions should happen: This is the issue!

The implementation of this method has worked very well in other situations when for example the FirebirdSQL service is restarted or when the database connection is lost for some network reason.

Another important piece of information is that the error message has changed since version 8.0.0:

Version 7.10.1 - Friday, December 4, 2020 (12/4/2020):
Unable to complete network request to host "
No message for error code 335544721 found.

Version 8.0.0 - Thursday, April 1, 2021 (4/1/2021):
Error writing data to the connection.
Error reading data from the connection.

Best Regards,
Luciano

**Comment by Ionut27** [comment] 2023-02-28 07:25
The message is the same as in this [issue](https://github.com/FirebirdSQL/NETProvider/issues/1021)
Behind could be another one that could help on resolving it

**Comment by cincuranet** [comment] 2023-02-28 13:53
@luronumen Can you also upload database (or at least structure to run your example)?

**Comment by luronumen** [comment] 2023-02-28 23:05
Hi @cincuranet 

I have attached the [NETProvider_1095.zip](https://github.com/FirebirdSQL/NETProvider/files/10855498/NETProvider_1095.zip) _.NET 7.0 console application_ containing:
- **FB30_DDL.SQL**: Script to create the Database;
- **BOTSERVICE_CIN.FDB**: The created database (FirebirdSQL 3.0)
- **Program.cs**: .NET console application to reproduce the issue

Please let me know if you also able to reproduce the issue.

Best Regards,
Luciano

**Comment by cincuranet** [comment] 2023-03-03 08:57
OK, the problem is that in this case the connection is "closed gracefully" from server-side ("connection shutdown" response) and because that's not broken socket (yet), the connection goes back to pool. Retrying again would solve it itself. But it should be handled nevertheless.

**Comment by luronumen** [comment] 2023-03-03 11:07
Hi @cincuranet 

Many thanks for debugging this issue!

As you can see in the _Program.cs_ class, the _SelectProcedure_ method automatically makes a second attempt (line 26) when the first attempt fails (line 20) but the connection is not reestablished: This is the bug!

I have a service running on Windows and in some cases this reconnection only happens after several minutes as you can see in the log below:

![Log](https://user-images.githubusercontent.com/8019466/222704355-a1f2229a-43b7-44e3-9d02-2d683a51a03b.png)

Please let me know when a fix for this bug is available so I can help you retest it.

Best Regards,
Luciano

**Comment by cincuranet** [comment] 2023-03-03 11:15
> As you can see in the Program.cs class, the SelectProcedure method automatically makes a second attempt (line 26) when the first attempt fails (line 20) but the connection is not reestablished: This is the bug!

You'd need to retry for 3rd time.

**Comment by luronumen** [comment] 2023-03-03 11:37
Hi @cincuranet 

Is trying a third time a temporary workaround or is the current behavior not considered a bug?

**Comment by cincuranet** [comment] 2023-03-03 20:07
In your case the 3rd retry is workaround. Regarding bug, yes, it's a bug.

**Comment by cincuranet** [comment] 2023-03-03 20:23
Closing in favor if specific #1097.

**Closed by cincuranet** 2023-03-03 20:23 UTC
Labels: component: ado.net provider

**Comment by luronumen** [comment] 2023-03-03 20:28
Hi @cincuranet 

Thank you very much for the confirmation!
Please let me know when you have the fix so I can help you validate it.

Meanwhile I will use the workaround replacing the _line 25_:
> if (poolingStatus)

by
> if (poolingStatus || fbException.ErrorCode == 335544727) //See https://github.com/FirebirdSQL/NETProvider/issues/1095

Best Regards,
Luciano

**Comment by cincuranet** [comment] 2023-03-03 20:32
> Please let me know when you have the fix so I can help you validate it.

Keep watching #1095 and you'll catch when it's done.

**Comment by Ionut27** [comment] 2025-02-17 13:51
I got that error on  a  remote db(net 4.8) where  Compression=True was set in the connection string but not [enabled on server](https://www.tabsoverspaces.com/233572-compression-support-in-firebirdclient-beta) 
it worked well as long as the number of resulting recordings was small
removing Compression=True fixed the problem
