### ISSUE TITLE
Support for bulk loading in Firebird 4

### ISSUE THREAD

**Issue by masonwheeler** [FirebirdSQL/NETProvider#962] opened 2021-06-25 12:12 UTC
The ability to bulk-load data is basically a standard feature in ADO.NET.  [SQL Server has it.](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy?view=dotnet-plat-ext-5.0)  So does [MySQL.](https://mysqlconnector.net/api/mysqlconnector/mysqlbulkcopytype/)  And [Postgres,](https://www.npgsql.org/doc/copy.html) and [Oracle](https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleBulkCopyClass.htm#ODPNT7446).  And with the exception of Postgres, they all seem to do it the same way: a "Bulk Copy" class that accepts the developer's choice of a `IDataReader`, a `DataTable`, or a `DataRow[]` as input.

`FirebirdClient` still lacks this feature.  With the new Firebird 4 OO API providing apis for batch data loading, could we get a Bulk Copy class added?

**Comment by cincuranet** [comment] 2021-06-25 12:20
Duplicate of #878.

**Closed** 2021-06-25 12:20 UTC
Labels: component: ado.net provider, resolution: duplicate
