### ISSUE TITLE
Scaffolding error with Firebird 2.5 with Numeric columns

### ISSUE THREAD

**Issue by lvalgimigli** [FirebirdSQL/NETProvider#1142] opened 2023-11-14 13:03 UTC
When i try to scaffold a Firebird 2.5 Database i get this error:  
 **Could not find type mapping for column 'XXXXXX' with data type 'NUMERIC(4,2)'. Skipping column.**  
My project references are:  FirebirdSql.EntityFrameworkCore.Firebird (10.0.0),  EntityFramework.Firebird(10.0.0) ,   
EntityFramework.Firebird (10.0.0)

**Comment by lvalgimigli** [comment] 2023-11-15 14:02
For my project i have used the last stable version of all libraries (10.0.0), have you a new version?

**Comment by cincuranet** [comment] 2024-11-07 10:50
Dupe of #1141.

**Closed by cincuranet** 2024-11-07 10:50 UTC
Labels: resolution: duplicate
