### ISSUE TITLE
EntityFrameworkCore Scaffolding: Increase maximum identifier lenght for Firebird 4.0

### ISSUE THREAD

**Issue by bgrauer-atacom** [FirebirdSQL/NETProvider#1132] opened 2023-08-16 08:25 UTC
The maximum identifier length has changed from [31 characters in version 3](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html#fblangref30-structure-identifiers) to [63 characters in version 4](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-structure-identifiers).

The [FbConventionSetBuilder](https://github.com/FirebirdSQL/NETProvider/blob/f169563ec05067c55974d2dfe09ff4f64cfd05d9/src/FirebirdSql.EntityFrameworkCore.Firebird/Metadata/Conventions/FbConventionSetBuilder.cs#L37) has a RelationalMaxIdentifierLengthConvention which is still set to 31. This can lead to unwanted name cuts when using Scraffolding.

**Comment by cincuranet** [comment] 2023-08-16 08:29
Duplicate of https://github.com/FirebirdSQL/NETProvider/issues/931.

**Closed by cincuranet** 2023-08-16 08:29 UTC
Labels: component: entity framework core

**Comment by bgrauer-atacom** [comment] 2023-08-16 14:13
There is a workaround which can be applied to the DbContext to increase the length:

``` csharp
    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        base.ConfigureConventions(configurationBuilder);
        configurationBuilder.Conventions.Replace((services) =>
        {
            var dependencies = services.GetRequiredService<ProviderConventionSetBuilderDependencies>();
            var relationalDependencies = services.GetRequiredService<RelationalConventionSetBuilderDependencies>();
            return new RelationalMaxIdentifierLengthConvention(63, dependencies, relationalDependencies);
        });
    }
```
