### ISSUE TITLE
[Firebird 3.0] [FirebirdClient 9.1.1] [FbTrace] ServiceOutput is not working

### ISSUE THREAD

**Issue by wryczko** [FirebirdSQL/NETProvider#1098] opened 2023-03-27 11:22 UTC
Steps to reproduce:

**Given:**

Firebird 3.0 database setup:
- install Firebird Server 3.0.10 (x64) on Windows 10 with default configuration https://firebirdsql.org/en/firebird-3-0-10/ 
- create an empty database https://firebirdsql.org/manual/bk02ar08s06.html
- add some test table to a newly created database

.NET 6.0 Console App setup:
- create new console app (.NET 6.0) using `dotnet new console -f net6.0`
- add Firebird Client (9.1.1) package using `dotnet add package FirebirdSql.Data.FirebirdClient --version 9.1.1`
- configure FbTrace to look for all insert/update/delete sql statements
```
// Create new tracer instance
var trace = new FbTrace();

trace.ConnectionString = "database=[DB_PATH];user=SYSDBA;password=[Password]";
trace.ServiceOutput += (object? sender, ServiceOutputEventArgs e) =>
{
   Console.WriteLine("Logged: " + e.Message); // called only once with message "Trace session ID 1 started" and never again
};
trace.DatabasesConfigurations.Add(
   new FbDatabaseTraceConfiguration()
   {
      DatabaseName = string.Empty,
      Enabled = true,
      Events = FbDatabaseTraceEvents.StatementFinish,
      IncludeFilter = "%(INSERT|UPDATE|DELETE)%",
      TimeThreshold = TimeSpan.FromMilliseconds(0),
    });

trace.Start($"trace-{Guid.NewGuid()}");
```

**When:**
- New row is added to a table using any means

**Then:**

Expected behaviour:
-  trace.ServiceOutput handler's body `Console.WriteLine("Logged: " + e.Message);` is called every time there is an insert/update/delete statement executed on database

Current behaviour:
- trace.ServiceOutput handler is called only once at trace start and never again

Additional info: 
- Provided solution works with Firebird 2.5
- I've noticed that Trace mechanism has been updated in Firebird 3.0, but I don't know if I should change something in my setup https://www.firebirdsql.org/rlsnotesh/rlsnotes30.html
- according to https://github.com/FirebirdSQL/firebird/issues/7518 potential problem might be with missing remote protocol prefix when defining a service name

**Comment by cincuranet** [comment] 2023-12-10 14:19
Thanks for reporting this. Turns out the new format (both supported in FirebirdClient) of trace config now requires only double quotes, while previously single and double quotes were accepted. Here's #1149 the issue tracking the root cause. I'll close this now.

**Closed by cincuranet** 2023-12-10 14:19 UTC
Labels: component: ado.net provider, type: bug, priority: minor
