### ISSUE TITLE
operation=... (Parameter 'operation')

### ISSUE THREAD

**Issue by konstantinLyang** [FirebirdSQL/NETProvider#1187] opened 2024-08-05 03:12 UTC
WEB API .net 8

It occurs at a random moment, regardless of anything. What should I do? Occurs frequently.

using Dapper 2.1.42 and FirebirdClient 10.3.1

StackTrace:
at FirebirdSql.Data.Client.Managed.GdsConnection.ProcessOperation(Int32 operation)
at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadSingleResponse(Int32 operation)
at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadSingleResponse()
at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadResponse()
at FirebirdSql.Data.Client.Managed.Version10.GdsTransaction.BeginTransaction(TransactionParameterBuffer tpb)
at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.BeginTransaction(TransactionParameterBuffer tpb)
at FirebirdSql.Data.FirebirdClient.FbTransaction.BeginTransaction()
at FirebirdSql.Data.FirebirdClient.FbCommand.Prepare(Boolean returnsSet)
at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommand(CommandBehavior behavior, Boolean returnsSet)
at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReader(CommandBehavior behavior)
at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteDbDataReader(CommandBehavior behavior)

A template example where an error occurs:

`public async Task<IEnumerable<Region>> GetAllAsync(CancellationToken ct)
    {
        await using var connection = new FbConnection(_configuration.GetConnectionString(ConnectionString));
        
        await connection.OpenAsync(ct);

        var command = new CommandDefinition(
            "SELECT DISTINCT REGION_ID as Id, REGION_NAME as Name FROM SPR_REGION",
            cancellationToken: ct);

        return await connection.QueryAsync<Region>(command);
    }`
how to fix it and what i can help, @cincuranet ?

**Comment by cincuranet** [comment] 2024-08-05 05:59
Dupe of #963.

**Closed by cincuranet** 2024-08-05 05:59 UTC
Labels: component: ado.net provider, resolution: duplicate
